/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janpixfarma;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import janpixfarma.modules.application.BootStrap;

/**
 *
 * @author Administrador
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public static int indexCliente = 0;
    DefaultTableModel model = null;
    public int itenSelec = -1;
    public boolean bandera;

    public Cliente() {
        initComponents();
        estadoBontones(true);
        estadoCajas(false);
        model = (DefaultTableModel) tbDetalle.getModel();
        if (BootStrap.Clientes.length >= 0) {
            for (int i = 0; i < BootStrap.Clientes.length; i++) {
                if (BootStrap.Clientes[i][0] != null) {
                    llenarGria(BootStrap.Clientes[i][0], BootStrap.Clientes[i][1], BootStrap.Clientes[i][2], BootStrap.Clientes[i][3], BootStrap.Clientes[i][4]);
                    indexCliente++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetalle = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de Clientes ");

        jLabel1.setText("DNI");

        jLabel2.setText("APELLIDOS");

        jLabel3.setText("NOMBRES");

        jLabel4.setText("BONUS");

        btNuevo.setText("NUEVO");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btEliminar.setText("ELIMINAR");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        tbDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "DNI", "APELLIDOS", "NOMBRES", "BONUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDetalle);

        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNuevo)
                                .addGap(24, 24, 24)
                                .addComponent(btGuardar)
                                .addGap(23, 23, 23)
                                .addComponent(btEliminar)
                                .addGap(10, 10, 10)
                                .addComponent(btCancelar)
                                .addGap(16, 16, 16)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellidos)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNuevo)
                    .addComponent(btGuardar)
                    .addComponent(btEliminar)
                    .addComponent(btCancelar)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void estadoBontones(boolean estado) {
        this.btNuevo.setEnabled(estado);
        this.btGuardar.setEnabled(!estado);
        this.btCancelar.setEnabled(!estado);
        this.btEliminar.setEnabled(estado);
        this.btEditar.setEnabled(estado);
    }

    private void estadoCajas(boolean estado) {
        this.txtDNI.setEnabled(estado);
        this.txtApellidos.setEnabled(estado);
        this.txtNombres.setEnabled(estado);
        this.txtBonus.setEnabled(estado);

    }

    private void limpiar() {
        this.txtDNI.setText(null);
        this.txtApellidos.setText(null);
        this.txtNombres.setText(null);
        this.txtBonus.setText(null);

    }

    private void llenarGria(String item, String dni, String apellidos, String nombres, String bonus) {
        model.addRow(new Object[]{item, dni, apellidos, nombres, bonus});

    }

    private boolean BuscaCodigo() {
        boolean ExisteCodigo = false;
        for (int i = 0; i < BootStrap.Clientes.length; i++) {
            if (txtDNI.getText().toUpperCase() != null && txtDNI.getText().toUpperCase().equals(BootStrap.Clientes[i][1])) {
                ExisteCodigo = true;
                break;
            }
        }
        return ExisteCodigo;
    }

    public static int BuscaDNI(String dni) {
        int indice = -1;
        for (int i = 0; i < BootStrap.Clientes.length; i++) {
            if (dni.toUpperCase() != null && dni.toUpperCase().equals(BootStrap.Clientes[i][1])) {
                indice = i;
                break;
            }
        }
        return indice;
    }

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        estadoBontones(false);
        estadoCajas(true);
        limpiar();
        bandera = true;
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        if (bandera) {
            if (BuscaCodigo()) {
                JOptionPane.showMessageDialog(null, "EL DNI YA EXISTE");
            } else {
                BootStrap.Clientes[indexCliente][0] = "" + (indexCliente+1);
                BootStrap.Clientes[indexCliente][1] = txtDNI.getText().toUpperCase();
                BootStrap.Clientes[indexCliente][2] = txtApellidos.getText().toUpperCase();
                BootStrap.Clientes[indexCliente][3] = txtNombres.getText().toUpperCase();
                BootStrap.Clientes[indexCliente][4] = txtBonus.getText().toUpperCase();
                llenarGria(BootStrap.Clientes[indexCliente][0], BootStrap.Clientes[indexCliente][1], BootStrap.Clientes[indexCliente][2], BootStrap.Clientes[indexCliente][3], BootStrap.Clientes[indexCliente][4]);
                indexCliente++;
                estadoBontones(true);
                estadoCajas(false);
                limpiar();
            }
        } else {

            BootStrap.Clientes[itenSelec][1] = txtDNI.getText().toUpperCase();
            BootStrap.Clientes[itenSelec][2] = txtApellidos.getText().toUpperCase();
            BootStrap.Clientes[itenSelec][3] = txtNombres.getText().toUpperCase();
            BootStrap.Clientes[itenSelec][4] = txtBonus.getText().toUpperCase();

            model.setValueAt(BootStrap.Clientes[itenSelec][1], itenSelec, 1);
            model.setValueAt(BootStrap.Clientes[itenSelec][2], itenSelec, 2);
            model.setValueAt(BootStrap.Clientes[itenSelec][3], itenSelec, 3);
            model.setValueAt(BootStrap.Clientes[itenSelec][4], itenSelec, 4);
            estadoBontones(true);
            estadoCajas(false);
            limpiar();
        }

    }//GEN-LAST:event_btGuardarActionPerformed

    private void tbDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDetalleMouseClicked
        itenSelec = tbDetalle.getSelectedRow();
        txtDNI.setText(BootStrap.Clientes[itenSelec][1]);
        txtApellidos.setText(BootStrap.Clientes[itenSelec][2]);
        txtNombres.setText(BootStrap.Clientes[itenSelec][3]);
        txtBonus.setText(BootStrap.Clientes[itenSelec][4]);
    }//GEN-LAST:event_tbDetalleMouseClicked

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        model.removeRow(itenSelec);
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        estadoBontones(true);
        estadoCajas(false);
        limpiar();
        bandera = false;
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (itenSelec != -1) {
            estadoBontones(false);
            estadoCajas(true);

            bandera = false;
        }
    }//GEN-LAST:event_btEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbDetalle;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
