/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package janpixfarma;

/**
 *
 * @author nickyop
 */
public class rankVentas extends javax.swing.JFrame {

    /**
     * Creates new form rankVentas
     */
    public rankVentas() {
        initComponents();
    }
    
    public String venta[][] = {
                            {"Pepito","Juan Perez","libertad 749 magdalena","viagra","12","120.20","01/03/2015"},
                            {"Juanito","Mguel Ramos","libertad 749 magdalena","Amoxilina","20","25.43","05/03/2015"},
                            {"Carlitos","Julian Gonzales","libertad 749 magdalena","Panadol","12","100","07/03/2015"},
                            {"Jaimito","Ramon Sanchez","libertad 749 magdalena","Apronax","12","14.10","09/03/2015"},
                            {"Pepito","Juan Perez","libertad 749 magdalena","Ampromox","12","180.30","11/03/2015"},
                            {"Jaimito","Juan Gonzales","libertad 749 magdalena","Supositorio","12","80.45","15/03/2015"},
                            {"Pepito","Ramon Sanchez","libertad 749 magdalena","Cloro Alergan","12","100.30","16/03/2015"},
                            {"Carlitos","Manuel Pineda","libertad 749 magdalena","Alcohol","12","300.80","17/03/2015"},
                            {"Pepito","Pedro Barboza","libertad 749 magdalena","PBM","12","120.50","19/03/2015"},
                            {"Juanito","Fernando Vallejos","libertad 749 magdalena","Penicilina 10000","12","190.14","22/03/2015"},
                           };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCanCar = new javax.swing.JLabel();
        lblCanJai = new javax.swing.JLabel();
        lblCanJua = new javax.swing.JLabel();
        lblCanPep = new javax.swing.JLabel();
        prbCarl = new javax.swing.JProgressBar();
        prbJaim = new javax.swing.JProgressBar();
        prbJuan = new javax.swing.JProgressBar();
        prbPepi = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Vendedor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nº Ventas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Porcentaje");

        jLabel4.setText("Carlitos");

        jLabel5.setText("Jaimito");

        jLabel6.setText("Juanito");

        jLabel7.setText("Pepito");

        lblCanCar.setText("jLabel8");

        lblCanJai.setText("jLabel9");

        lblCanJua.setText("jLabel10");

        lblCanPep.setText("jLabel11");

        prbCarl.setStringPainted(true);

        prbJaim.setStringPainted(true);

        prbJuan.setStringPainted(true);

        prbPepi.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCanCar)
                                    .addComponent(lblCanJai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prbJaim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prbCarl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prbJuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prbPepi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCanPep)
                            .addComponent(lblCanJua))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblCanCar))
                    .addComponent(prbCarl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCanJai)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(prbJaim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblCanJua)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prbJuan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lblCanPep))
                    .addComponent(prbPepi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int canCarl = 0;
        int canJaim = 0;
        int canJuan = 0;
        int canPepi = 0;
        
        int pCarl = 0;
        int pJaim = 0;
        int pJuan = 0;
        int pPepi = 0;
        
        for(int i=0; i<venta.length; i++)
        {
            if(venta[i][0].equalsIgnoreCase("Carlitos"))
                canCarl = canCarl + 1;
            else if(venta[i][0].equalsIgnoreCase("Jaimito"))
                canJaim = canJaim + 1;
            else if(venta[i][0].equalsIgnoreCase("Juanito"))
                canJuan = canJuan + 1;
            else if(venta[i][0].equalsIgnoreCase("Pepito"))
                canPepi = canPepi + 1;
        }
        
        lblCanCar.setText(String.valueOf(canCarl));
        pCarl = (int)((canCarl*100)/venta.length);
        prbCarl.setValue(pCarl);
        
        lblCanJai.setText(String.valueOf(canJaim));
        pJaim = (int)((canJaim*100)/venta.length);
        prbJaim.setValue(pJaim);
        
        lblCanJua.setText(String.valueOf(canJuan));
        pJuan = (int)((canJuan*100)/venta.length);
        prbJuan.setValue(pJuan);
        
        lblCanPep.setText(String.valueOf(canPepi));
        pPepi = (int)((canPepi*100)/venta.length);
        prbPepi.setValue(pPepi);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rankVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCanCar;
    private javax.swing.JLabel lblCanJai;
    private javax.swing.JLabel lblCanJua;
    private javax.swing.JLabel lblCanPep;
    private javax.swing.JProgressBar prbCarl;
    private javax.swing.JProgressBar prbJaim;
    private javax.swing.JProgressBar prbJuan;
    private javax.swing.JProgressBar prbPepi;
    // End of variables declaration//GEN-END:variables
}
