/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janpixfarma;


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Cesar R
 */
public class ReporteCompras extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteCompras
     */
    
    /*
    Datos de usuario para hacer pruebas    
    */       
   static  String unombres = "Cesar"; //Guarda el nombre del usuario
   static  String uapellidos = "Rubinos";//Gurda en apellido del usuario
   static  String udni = "400670985"; //Guarda el DNI del usuario
   
   
  // public static String clientes[][] = new String[20][4];  //Matriz donde guarda los datos del cliente                                           
   public static String medicamentos[][] = new String[20][7]; //Matriz donde se guardan los datos de medicamento                                         
  // public static String ventas[][] = new String[20][7]; //Matriz donde se guardan los datos de las ventas  
    
   DefaultTableModel modeloReporteCompras; //Se crea una tabla a partir del modelo standar
   String datosCompras[] = new String[3];  //Arreglo para mostrar datos en la lista         

                    
    
    public ReporteCompras() {
        
        initComponents();
        
        modeloReporteCompras = new DefaultTableModel();//Se instancia nuestro modelo de tabla
        modeloReporteCompras.addColumn("Medicamento");//Se crea la columna "medidamento" en la tabla
        modeloReporteCompras.addColumn("Stock de medicamento");//Se crea la columna "monto recaudado" en la tabla    
        modeloReporteCompras.addColumn("Fecha de vencimiento");
        this.libReporteCompras.setModel(modeloReporteCompras);  
        lblUsuario.setText(unombres+ " " +uapellidos);//Muestra el nombre y apellido del usuario
    }
                       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        libReporteCompras = new javax.swing.JTable();
        btnProcesar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnVentanaPrincipal = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Compras");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Usuario: ");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        libReporteCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(libReporteCompras);

        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnVentanaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentanaPrincipal.setText("Ventana Principal");
        btnVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:\
      
       /*
     * Matriz para medicamento. 
     * 0: Tipo medicamento.
     * 1: Presentación medicamento. 
     * 2: Nombre medicamento. 
     * 3: Compuesto Quimico 
     * 4: Cantidad. 
     * 5: Precio Unitario. 
     * 6: Fecha Vencimiento.
     */
      medicamentos[1][0]="Pastillas";
      medicamentos[1][1]="Caja";
      medicamentos[1][2]="Apronax";
      medicamentos[1][3]="Ibuprofeno";
      medicamentos[1][4]="20";
      medicamentos[1][5]="2.5";
      medicamentos[1][6]="25/03/15";
      
      medicamentos[2][0]="Pastillas";
      medicamentos[2][1]="Caja";
      medicamentos[2][2]="Dolocordralan";
      medicamentos[2][3]="AnalgesicPT";
      medicamentos[2][4]="300";
      medicamentos[2][5]="2.5";
      medicamentos[2][6]="30/07/14";
      
      medicamentos[3][0]="Pastillas";
      medicamentos[3][1]="Caja";
      medicamentos[3][2]="Portil";
      medicamentos[3][3]="Antimicotico";
      medicamentos[3][4]="40";
      medicamentos[3][5]="2.5";
      medicamentos[3][6]="30/12/15";
        
      
      medicamentos[19][0]="Pastillas";
      medicamentos[19][1]="Caja";
      medicamentos[19][2]="Portil";
      medicamentos[19][3]="Antimicotico";
      medicamentos[19][4]="600";
      medicamentos[19][5]="2.5";
      medicamentos[19][6]="25/03/15";
               
        
      Date fechaActual = new Date();//Guarda la fecha actual del sistema
      Date fechaVenc = new Date();//Guarda la fecha de vencimiento del medicamento
      
      /*
      Busqueda en la matriz de venta de acuerdo a la cantidad de stock y a la fecha de vencimiento
      del medicamento. Las coincidencias son luego mostradas en la tabla.
      */
      
      
        for (int i = 0; i < medicamentos.length; i++) {
             if (medicamentos[i][0] != null) {
                 String stringActual = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
                 
                 try {
                     fechaActual = new SimpleDateFormat("dd/MM/yyyy").parse(stringActual);
                 } catch (ParseException ex) {
                     Logger.getLogger(ReporteCompras.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
                 
                 try {
                     fechaVenc = new SimpleDateFormat("dd/MM/yyyy").parse(medicamentos[i][6]);
                 } catch (ParseException ex) {
                     Logger.getLogger(ReporteCompras.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 
            if (Integer.parseInt(medicamentos[i][4]) < 50){                
                    System.out.println(medicamentos[i][2] + "\t" + medicamentos[i][4] + "\t" + medicamentos[i][6]);
                    datosCompras[0]=medicamentos[i][2];//Nombre del medicamento
                    datosCompras[1]=medicamentos[i][4];//Cantidad de stock
                    datosCompras[2]=medicamentos[i][6];//Fecha de vencimiento
                     modeloReporteCompras.addRow(datosCompras);
                }                                                     
             }                          
      }                                                                                                      
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
         int cantidadFilas = modeloReporteCompras.getRowCount();//Borra la lista cuando se pulse el boton Borrar
        for(int i=cantidadFilas-1; i>=0; i--){
            modeloReporteCompras.removeRow(i);
        }
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPrincipalActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);//Se habilita la opcion visible del objeto creado
        dispose();//Oculta la ventana principal.
    }//GEN-LAST:event_btnVentanaPrincipalActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnVentanaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable libReporteCompras;
    // End of variables declaration//GEN-END:variables
}
